# Generated by Django 5.0.2 on 2024-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='altphnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='phnumber',
            field=models.IntegerField(),
        ),
    ]
