# Generated by Django 5.0.2 on 2024-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_students_altphnumber_alter_students_phnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='altphnumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='phnumber',
            field=models.CharField(max_length=20),
        ),
    ]
