# Generated by Django 5.0.2 on 2024-03-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_students_altphnumber_alter_students_phnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kathabooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phnumber', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('timeofday', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
    ]
